influxdb:
  image: influxdb:1.8.4
  container_name: influxdb
  restart: always
#  mem_limit: 192m
# Those ports don't need to be exposed to the local host, only
# Telegraf/grafana are talking to it.
#  ports:
#    - "8083:8083"
#    - "8086:8086"
#    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistency
    - ./influxdb/data:/var/lib/influxdb
    # Configuration
    - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro

telegraf:
  image: telegraf:latest
  container_name: telegraf
  restart: always
  environment:
   - HOST_PROC=/host/proc
  privileged: true
#  mem_limit: 384m
  ports:
    # Expose Statsd UDP server to local host
    - "8125:8125/udp"
  links:
    - influxdb
  volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /proc:/host/proc:ro
    - /var/log:/host/var/log:ro

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  restart: always
#  mem_limit: 384m
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
    - ./grafana/data:/var/lib/grafana
    - ./grafana/provisioning:/etc/grafana/provisioning
