{
 "title": "AX25 By station",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "callsign",
    "label": "Callsign",
    "query": "SELECT distinct(\"callsign\") FROM (select * from  \"ax25_listen\" WHERE $timeFilter)"
   }
  ]
 },
 "panels": [
  {
   "title": "Frames",
   "type": "graph",
   "description": "Number of AX25 frames",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Packets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ax25_listen",
     "select": [
      [
       { "params": [ "interface" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "callsign", "operator": "=~", "value": "/^$callsign$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic per station",
   "type": "graph",
   "description": "Number of bytes sent by each station. Hover over the bars for individual details.",
   "gridPos": { "h": 15, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_callsign",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "callsign" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ax25_listen",
     "query": "SELECT count(\"utime\") AS \"Frames\", last(\"system\") AS \"System\" FROM \"ax25_packet\" WHERE $timeFilter GROUP BY \"source\"",
     "select": [
      [
       { "params": [ "length" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "callsign", "operator": "=~", "value": "/^$callsign$/" }
     ]
    }
   ]
  },
  {
   "title": "Destinations",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "measurement": "ax25_listen",
     "query": "SELECT distinct(\"destination\") FROM \"ax25_listen\" WHERE (\"callsign\" =~ /^$callsign$/) AND $timeFilter GROUP BY \"callsign\"",
     "select": [
      [
       { "params": [ "destination" ], "type": "field" }
      ],
      [
       {
        "params": [
         "\"callsign\""
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "callsign", "operator": "=~", "value": "/^$callsign$/" }
     ]
    }
   ]
  },
  {
   "title": "Stations heard direct",
   "type": "table",
   "description": "Stations received directly (determined as stations where we have an empty \"repeated\" path",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "callsign",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ax25_listen",
     "query": "select distinct(\"callsign\") from (select * from ax25_listen WHERE $timeFilter  fill(-1) ) where ax25path_repeated=-1 AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes transfered",
   "type": "stat",
   "description": "Total number of bytes sent by all the stations over this time period",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ax25_listen",
     "select": [
      [
       { "params": [ "length" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "callsign", "operator": "=~", "value": "/^$callsign$/" }
     ]
    }
   ]
  },
  {
   "title": "Frames detail",
   "type": "table",
   "description": "Traffic info for selected stations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "repeat": "callsign",
   "targets": [
    {
     "measurement": "ax25_listen",
     "select": [
      [
       { "params": [ "callsign" ], "type": "field" }
      ],
      [
       { "params": [ "destination" ], "type": "field" }
      ],
      [
       { "params": [ "ax25path" ], "type": "field" }
      ],
      [
       { "params": [ "ctl" ], "type": "field" }
      ],
      [
       { "params": [ "ax25pid" ], "type": "field" }
      ],
      [
       { "params": [ "length" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "callsign", "operator": "=~", "value": "/^$callsign$/" }
     ]
    }
   ]
  },
  {
   "title": "Frames detail",
   "type": "table",
   "description": "Traffic info for selected stations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "measurement": "ax25_listen",
     "select": [
      [
       { "params": [ "callsign" ], "type": "field" }
      ],
      [
       { "params": [ "destination" ], "type": "field" }
      ],
      [
       { "params": [ "ax25path" ], "type": "field" }
      ],
      [
       { "params": [ "ctl" ], "type": "field" }
      ],
      [
       { "params": [ "ax25pid" ], "type": "field" }
      ],
      [
       { "params": [ "length" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "callsign", "operator": "=~", "value": "/^$callsign$/" }
     ]
    }
   ]
  },
  {
   "title": "Frames detail",
   "type": "table",
   "description": "Traffic info for selected stations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "measurement": "ax25_listen",
     "select": [
      [
       { "params": [ "callsign" ], "type": "field" }
      ],
      [
       { "params": [ "destination" ], "type": "field" }
      ],
      [
       { "params": [ "ax25path" ], "type": "field" }
      ],
      [
       { "params": [ "ctl" ], "type": "field" }
      ],
      [
       { "params": [ "ax25pid" ], "type": "field" }
      ],
      [
       { "params": [ "length" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "callsign", "operator": "=~", "value": "/^$callsign$/" }
     ]
    }
   ]
  },
  {
   "title": "Frames detail",
   "type": "table",
   "description": "Traffic info for selected stations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "measurement": "ax25_listen",
     "select": [
      [
       { "params": [ "callsign" ], "type": "field" }
      ],
      [
       { "params": [ "destination" ], "type": "field" }
      ],
      [
       { "params": [ "ax25path" ], "type": "field" }
      ],
      [
       { "params": [ "ctl" ], "type": "field" }
      ],
      [
       { "params": [ "ax25pid" ], "type": "field" }
      ],
      [
       { "params": [ "length" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "callsign", "operator": "=~", "value": "/^$callsign$/" }
     ]
    }
   ]
  },
  {
   "title": "Frames detail",
   "type": "table",
   "description": "Traffic info for selected stations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "measurement": "ax25_listen",
     "select": [
      [
       { "params": [ "callsign" ], "type": "field" }
      ],
      [
       { "params": [ "destination" ], "type": "field" }
      ],
      [
       { "params": [ "ax25path" ], "type": "field" }
      ],
      [
       { "params": [ "ctl" ], "type": "field" }
      ],
      [
       { "params": [ "ax25pid" ], "type": "field" }
      ],
      [
       { "params": [ "length" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "callsign", "operator": "=~", "value": "/^$callsign$/" }
     ]
    }
   ]
  },
  {
   "title": "Frames detail",
   "type": "table",
   "description": "Traffic info for selected stations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "measurement": "ax25_listen",
     "select": [
      [
       { "params": [ "callsign" ], "type": "field" }
      ],
      [
       { "params": [ "destination" ], "type": "field" }
      ],
      [
       { "params": [ "ax25path" ], "type": "field" }
      ],
      [
       { "params": [ "ctl" ], "type": "field" }
      ],
      [
       { "params": [ "ax25pid" ], "type": "field" }
      ],
      [
       { "params": [ "length" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "callsign", "operator": "=~", "value": "/^$callsign$/" }
     ]
    }
   ]
  }
 ]
}